# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChatBot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import stt as s
import Text_to_Audio as t
import learn_module as l

class Ui_MainWindow(object):
    def clicked(self):
        l.chat()
        return True


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Chat Bot")
        MainWindow.setGeometry(1720, 780, 200, 200)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 200, 200))
        self.pushButton.setStyleSheet("QPushButton#pushButton\n"
"{\n"
"border-radius: 100px;\n"
"border: 5px solid rgb(255, 255, 255) ;\n"
"color: rgb(255, 255, 232);\n"
"background-color: rgb(180, 0, 0);\n"
"}\n"
"QPushButton#pushButton:hover\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton#pushButton:pressed\n"
"{\n"
"color: rgb(255, 255, 232);\n"
"background-color: rgb(180, 0, 0);\n"
"border: 5px solid rgb(180, 0, 0) ;\n"
"}")
        self.pushButton.pressed.connect(self.clicked)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Push To Speak"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
