# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Loginapp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow 
import res
import sys

class Ui_Form(object):
    def __init__(self):
        super(Ui_Form, self).__init__()
        Form = QtWidgets.QWidget()
        self.setupUi(Form)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 500)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 500))
        self.label.setStyleSheet("background: rgb(2,0,36);\n"
"border-radius: 20px;")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(55, 290, 300, 35))
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(2,0,36);\n"
"color:rgb(255,255,255);\n"
"border: 1px solid rgb(2,0,36);\n"
"border-radius: 20px;\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-bottom-width: 1px;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(55, 350, 300, 40))
        self.pushButton.setStyleSheet("QPushButton#pushButton\n"
"{\n"
"border-radius: 10px;\n"
"color: rgb(255,255,255);\n"
"background: rgb(2,0,36);\n"
"border: 1px solid rgb(255,255,255);\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(0,0,0);\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(0,0,0);\n"
"border: 1px solid rgb(0,0,0)\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(127, 50, 150, 150))
        self.label_4.setStyleSheet("border-radius:20px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/Images/E2ABtHMWYAE9Pkp.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 400, 150, 40))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2\n"
"{\n"
"border-radius: none;\n"
"color: rgb(255,255,255);\n"
"background: rgb(2,0,36);\n"
"border: none;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"color: red;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"color: blue;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(55, 240, 300, 35))
        self.lineEdit.setStyleSheet("background-color: rgb(2,0,36);\n"
"color:rgb(255,255,255);\n"
"border: 1px solid rgb(2,0,36);\n"
"border-radius: 20px;\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-bottom-width: 1px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label.raise_()
        self.label_4.raise_()
        self.plainTextEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lineEdit.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def on_click(self):
        self.label.setText("Yes")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Background"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.pushButton_2.setText(_translate("Form", "Forgot Password?"))
        self.lineEdit.setText(_translate("Form", "User Name"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())